### ISSUE TITLE
Prestige

### ISSUE THREAD

**Issue by melodiouscat** [antdroidx/CFB-Coach#32]
I have the Android version and there seems to be an issue with prestige. I always get/lose less prestige every year than I'm supposed to. And then when I get to 77-79 Prestige I can't gain more. It will say I'm supposed to gain 6 or 7 prestige and then it just won't go up.

**Comment by antdroidx** [comment]
Are you sure this is a bug? I just simulated a bunch of seasons and prestige always matches up. There's nothing in my code that would change the prestige randomly - I checked every line.

If you read the news, you may be losing points in the offseason due to infractions.
You can also lose prestige or gain prestige at various points during the season, but you have to keep up on the weekly News pages to see it.

**Comment by antdroidx** [comment]
v1.0.5 just released on PlayStore. Should clarify/fix any issues with prestige.
