### ISSUE TITLE
Duplicate Players on Roster

### ISSUE THREAD

**Issue by dathomas1** [antdroidx/CFB-Coach#35]
![screenshot_2018-04-20-23-22-30](https://user-images.githubusercontent.com/3870598/39084697-f662c820-453e-11e8-881e-eac87771ae02.png)

This is the first time this happened in my Dynasty.

**Comment by antdroidx** [comment]
Whoa. That's weird. Did this happen in most recent update?

**Comment by dathomas1** [comment]
Yes, version 1.0.7. The app crashed then it reverted to the Recruiting Class ranking screen. I think clicked roster and that's when I saw the duplicates. The game continued normally. The game treated each duplicate as an actual player.

**Comment by antdroidx** [comment]
Something funny must have happened when it crashed. If you got the game from the Play Store, I've been looking at crash records that are sent to Google and trying to see if I can fix any bugs that pop up. That's definitely not something I've been able to repeat since I havent seen crashes at that screen in many months. I am in year 2040 in one of my saves.

**Comment by dathomas1** [comment]
This error hasn't occurred since. You can close this issue
