### ISSUE TITLE
Prestige/Coach

### ISSUE THREAD

**Issue by Chris2Charming** [antdroidx/CFB-Coach#48]
Prestige Gains seem like nothing more than a review of what you did with your talent. Thats a good way to evaluate coach performance. However, we don't evaluate a Teams Prestige by their expectations we evaluate by what they do. Prestige should grow or decay more like a straight line method with slight tilts for expectations based on past results not the current roster. If I take a 1-11 team and turn them into a 7-5 team by the following year the prestige of the program just rose. However if we were expected to go 7-5 or 8-4 then our Prestige wont grow. Thats just not how it actually works tho. 

Also, if a team such as Ohio State whom has the roster and track record to expect a championship finishes in the top 10 for 10 years in a row but never wins a championship their Prestige is still solidified with continued success. Alabama is a good example everyone also brings up do the championships. However if you look at LSU they maintain prestige until multiple seasons of disappointment. So Perhaps we should add a flat line Long Term Performance Prestige Increase/decrease.

I know the prestige system is the way things have always been done, and I do really well despite it. It just should be looked at

**Comment by antdroidx** [comment]
I have actually modified the prestige a lot since it's original version. If you stay in the Top 25, you will not lose prestige even if you are expected to be higher than 25. If you remain "good" you should not lose prestige, but if you have a poor season, you will. LSU, in real life, hasn't had terrible seasons, but they are not as highly looked upon as they had been 10 years ago. They are still good, even Top 25 good perhaps, but I dont think people consider them in the top 10 anymore. 

But, I am open to improving it. This has been the HARDEST challenge for me personally with this game. Getting the Prestige/Recruiting/Improvement of teams correct. That's why I've revamped it several times over now and I still struggle to make it perfect. I think the opening up of the prestige limit helps quite a bit because the good teams can continue to gain prestige and not limited. This helps. It's been a struggle keeping lower tier teams from rising too fast though.
